# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Lijun LI
tagline:          'A Jekyll theme'
description:      'To do justly, To love mercy, And to walk humbly with your God? (Micah6:8)'
baseurl:          /

author:
  name:           'Lijun LI'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
